"""Add integration fields to Channel model

Revision ID: e7f2ec314303
Revises: 3194c30ed9ba
Create Date: 2025-12-10 21:15:12.049376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f2ec314303'
down_revision: Union[str, Sequence[str], None] = '3194c30ed9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    channelstatus = sa.Enum('DISCONNECTED', 'CONNECTING', 'CONNECTED', 'ERROR', name='channelstatus')
    channelstatus.create(op.get_bind(), checkfirst=True)

    op.add_column('channels', sa.Column('user_id', sa.Integer(), nullable=True))  # Made nullable temporarily
    op.add_column('channels', sa.Column('status', channelstatus, nullable=True))
    op.add_column('channels', sa.Column('platform_account_id', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('platform_account_name', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('qr_code', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('qr_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('channels', sa.Column('last_error', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('error_count', sa.Integer(), nullable=True, server_default='0'))
    op.create_foreign_key('fk_channels_user_id', 'channels', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_channels_user_id', 'channels', type_='foreignkey')
    op.drop_column('channels', 'error_count')
    op.drop_column('channels', 'last_error')
    op.drop_column('channels', 'qr_code_expires_at')
    op.drop_column('channels', 'qr_code')
    op.drop_column('channels', 'refresh_token')
    op.drop_column('channels', 'platform_account_name')
    op.drop_column('channels', 'platform_account_id')
    op.drop_column('channels', 'status')
    op.drop_column('channels', 'user_id')

    # Drop the enum type
    sa.Enum(name='channelstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
